### ISSUE TITLE
Section 3.1 - Grammar fix

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-architecture#18]
version -03

s/be a target endpoint, or a component, or both simultaneously./be a target endpoint, a component or both simultaneously./

**Comment by llorenzin** [comment]
The serial comma you are suggesting to remove is necessary; it clarifies that these are three items in a sequence, rather than two items illustrating the initial item.  (See http://www.verbicidemagazine.com/2011/09/20/strippers-jfk-and-stalin-illustrate-why-you-should-use-the-serial-comma/ )

-----Original Message-----

**Comment by jimsch** [comment]
Feel free to keep the comma, I don't care about it.  I was objecting to the word 'or'.

**Comment by llorenzin** [comment]
Ah, thanks for clarifying! Second "or" removed in -04.

-----Original Message-----
